apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "nodepool_launcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nodepool_launcher
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.nodepool_launcher.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: nodepool_launcher
  serviceName: {{ include "nodepool_launcher.fullname" . }}
  updateStrategy:
    type: {{ .Values.nodepool_launcher.updateStrategy }}
    {{- if (eq "Recreate" .Values.nodepool_launcher.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.nodepool_launcher.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.nodepool_launcher.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "nodepool_launcher.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/nodepool_launcher/configmap.yaml") . | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nodepool_launcher
    spec:
      containers:
        - name: nodepool_launcher
          image: {{ include "nodepool_launcher.image" . }}
          imagePullPolicy: {{ .Values.nodepool_launcher.image.pullPolicy | quote }}
          command: {{ .Values.nodepool_launcher.command }}
          args: {{ .Values.nodepool_launcher.args }}
          ports:
            - name: nodepool
              containerPort: {{ .Values.nodepool_launcher.service.port }}
          volumeMounts:
            - name: ssh
              mountPath: /root/.ssh
  volumes:
    - name: ssh
      persistentVolumeClaim:
        claimName: 'zuul_ssh'
