{{- if .Values.mariadb.primary.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mariadb.primary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
    {{- if .Values.mariadb.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.mariadb.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mariadb.primary.pdb.minAvailable }}
  minAvailable: {{ .Values.mariadb.primary.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.mariadb.primary.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.mariadb.primary.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
{{- end }}