{{- if eq (include "mariadb.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.mariadb.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.mariadb.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not (empty .Values.mariadb.auth.rootPassword) }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  {{- else if (not .Values.mariadb.auth.forcePassword) }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  mariadb-root-password: {{ required "A MariaDB Root Password is required!" .Values.mariadb.auth.rootPassword }}
  {{- end }}
  {{- if and (not (empty .Values.mariadb.auth.username)) (not (empty .Values.mariadb.auth.password)) }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- else if (not .Values.mariadb.auth.forcePassword) }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.mariadb.auth.password }}
  {{- end }}
  {{- if eq .Values.mariadb.architecture "replication" }}
  {{- if not (empty .Values.mariadb.auth.replicationPassword) }}
  mariadb-replication-password: {{ .Values.mariadb.auth.replicationPassword | b64enc | quote }}
  {{- else if (not .Values.mariadb.auth.forcePassword) }}
  mariadb-replication-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  mariadb-replication-password: {{ required "A MariaDB Replication Password is required!" .Values.mariadb.auth.replicationPassword }}
  {{- end }}
  {{- end }}
{{- end }}