apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "zuul_executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zuul_executor
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.zuul_executor.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: zuul_executor
  serviceName: {{ include "zuul_executor.fullname" . }}
  updateStrategy:
    type: {{ .Values.zuul_executor.updateStrategy }}
    {{- if (eq "Recreate" .Values.zuul_executor.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.zuul_executor.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.zuul_executor.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "zuul_executor.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/zuul_executor/configmap.yaml") . | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: zuul_executor
    spec:
      containers:
        - name: zuul_executor
          image: {{ include "zuul_executor.image" . }}
          imagePullPolicy: {{ .Values.zuul_executor.image.pullPolicy | quote }}
          command: {{ .Values.zuul_executor.command }}
          args: {{ .Values.zuul_executor.args }}
          ports:
            - name: executor
              containerPort: {{ .Values.zuul_executor.service.port }}
          volumeMounts:
            - name: ssh
              mountPath: /root/.ssh
  volumes:
    - name: ssh
      persistentVolumeClaim:
        claimName: 'zuul_ssh'
