apiVersion: v1
kind: Service
metadata:
  name: {{ include "zuul_executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zuul_executor
  annotations:
    {{- if .Values.zuul_executor.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.zuul_executor.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: {{ .Values.zuul_executor.service.clusterIP }}
  ports:
    - name: executor
      port: 7900
      targetPort: executor
      nodePort: null
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: zuul_executor
