{{- if (include "zookeeper.createConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
data:
  zoo.cfg: |-
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=1000
    standaloneEnabled=true
    admin.enableServer=true
    server.1={{ .Values.zookeeper.fqdn }}:2888:3888
    serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    secureClientPort=2281
    ssl.keyStore.location=/var/certs/keystores/{{ .Values.zookeeper.fqdn }}.pem
    ssl.trustStore.location=/var/certs/certs/cacert.pem
{{- end -}}
