apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.zookeeper.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
  serviceName: {{ include "zookeeper.fullname" . }}
  updateStrategy:
    type: {{ .Values.zookeeper.updateStrategy }}
    {{- if (eq "Recreate" .Values.zookeeper.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.zookeeper.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.zookeeper.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "zookeeper.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/zookeeper/configmap.yaml") . | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
    spec:
      hostname: {{ .Values.zookeeper.fqdn }}
      containers:
        - name: zookeeper
          image: {{ include "zookeeper.image" . }}
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy | quote }}
          command: {{ .Values.zookeeper.command }}
          args: {{ .Values.zookeeper.args }}
          ports:
            - name: client
              containerPort: {{ .Values.zookeeper.service.port }}
            - name: client-tls
              containerPort: {{ .Values.zookeeper.service.tlsClientPort }}
            - name: follower
              containerPort: {{ .Values.zookeeper.service.followerPort }}
          volumeMounts:
            - name: data
              mountPath: /var/certs
            - name: config
              mountPath: /conf/zoo.cfg
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{ include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/component: zookeeper
      spec:
        accessModes:
          {{- range .Values.zookeeper.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.zookeeper.persistence.size | quote }}
        {{ include "common.storage.class" (dict "persistence" .Values.zookeeper.persistence "global" .Values.zookeeper.global) }}
