apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "worker_node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: worker_node
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.worker_node.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker_node
  serviceName: {{ include "worker_node.fullname" . }}
  updateStrategy:
    type: {{ .Values.worker_node.updateStrategy }}
    {{- if (eq "Recreate" .Values.worker_node.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.worker_node.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.worker_node.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "worker_node.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/worker_node/configmap.yaml") . | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: worker_node
    spec:
      containers:
        - name: worker_node
          image: {{ include "worker_node.image" . }}
          imagePullPolicy: {{ .Values.worker_node.image.pullPolicy | quote }}
          command: {{ .Values.worker_node.command }}
          args: {{ .Values.worker_node.args }}
          ports:
            - name: ssh
              containerPort: {{ .Values.worker_node.service.port }}
          volumeMounts:
            - name: ssh
              mountPath: /root/.ssh
  volumes:
    - name: ssh
      persistentVolumeClaim:
        claimName: 'zuul_ssh'
