apiVersion: {{ include "common.capabilities.staetfulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "zuul_scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zuul_scheduler
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.zuul_scheduler.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: zuul_scheduler
  serviceName: {{ include "zuul_scheduler.fullname" . }}
  updateStrategy:
    type: {{ .Values.zuul_scheduler.updateStrategy }}
    {{- if (eq "Recreate" .Values.zuul_scheduler.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.zuul_scheduler.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.zuul_scheduler.rollingUpdatePartition }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "zuul_scheduler.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/zuul_scheduler/configmap.yaml") . | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: zuul_scheduler
    spec:
      containers:
        - name: zuul_scheduler
          image: {{ include "zuul_scheduler.image" . }}
          imagePullPolicy: {{ .Values.zuul_scheduler.image.pullPolicy | quote }}
          command: {{ .Values.zuul_scheduler.command }}
          args: {{ .Values.zuul_scheduler.args }}
          ports:
            - name: gearman
              containerPort: {{ .Values.zuul_scheduler.service.port }}
          volumeMounts:
            - name: ssh
              mountPath: /root/.ssh
  volumes:
    - name: ssh
      persistentVolumeClaim:
        claimName: 'zuul_ssh'
