apiVersion: v1
kind: Service
metadata:
  name: {{ include "zuul_scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zuul_scheduler
  annotations:
    {{- if .Values.zuul_scheduler.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.zuul_scheduler.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: {{ .Values.zuul_scheduler.service.clusterIP }}
  ports:
    - name: gearman
      port: 4730
      targetPort: gearman
      nodePort: null
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: zuul_scheduler
